###
POST http://localhost:8080/api/records
Content-Type: application/json

{
    "value":"${PROTOCOL}://${HOST:localhost}/${PATH}"
}

###
POST http://localhost:8080/api/placeholders
Content-Type: application/json

{
    "name": "PROTOCOL",
    "value": "https"
}

###
GET http://localhost:8080/api/records

###
GET http://localhost:8080/api/placeholders